jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup OCaml & OPAM
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1
          opam-repositories: default
          opam-pin: "mini-pytype=."
          opam-depext: "true"
          dune-cache: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install OPAM deps
        run: opam install . --deps-only -y

      - name: Dune build
        run: dune build --profile=release

      - name: Dune runtest
        run: dune runtest
